version: "3.8"

services:
  api:
    env_file:
      - .env
    build: .
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}

  dashboard:
    env_file:
      - .env
    build: .
    command: streamlit run src/dashboard.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    environment:
      - API_KEY=${API_KEY}
    depends_on:
      - api
